version: "3.9"

services:
  bot:
    build:
      context: .
    restart: unless-stopped
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: '${MONGO_DB_USER}'
      MONGO_INITDB_ROOT_PASSWORD: '${MONGO_DB_PASSWORD}'

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: '${MONGO_DB_USER}'
      ME_CONFIG_MONGODB_ADMINPASSWORD: '${MONGO_DB_PASSWORD}'
      ME_CONFIG_MONGODB_URL: 'mongodb://${MONGO_DB_USER}:${MONGO_DB_PASSWORD}@${MONGO_DB_HOST}:${MONGO_DB_PORT}/'
